spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
---
spring:
  application:
    name: department-service
  config:
    import: "optional:configserver:http://localhost:8088"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Microservices